CREATE TABLE IF NOT EXISTS faq_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(512) NOT NULL,
  answerText LONGTEXT NOT NULL,
  content LONGTEXT NOT NULL,
  images JSON,
  embedding LONGTEXT,
  bm25Terms LONGTEXT,
  tags JSON,
  createdBy INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX faq_entries_createdBy_idx (createdBy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

